'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const source = fs.readFileSync(path.join(__dirname, '../web/extra.js'), 'utf8');
const notices = [];
const windowObj = {GD: {}, UI: {}, GDStore: {toast: (...args) => notices.push(args)}};
vm.runInNewContext(source, {window: windowObj, React: {useState() {}, createElement() {}}, Blob, URL});
const ui = windowObj.TemplateUI;
assert.throws(() => ui.parseTemplateBundle('{broken'), /JSON/);
assert.throws(() => ui.parseTemplateBundle(JSON.stringify({format:'something-else', version:1})), /bundle/);
const bundle = {format:'goblindock-template',version:1,template:{name:'demo'},customBlocks:[]};
assert.equal(ui.parseTemplateBundle(JSON.stringify(bundle)).template.name, 'demo');
assert.throws(() => ui.templateImportPayload(bundle, '', '', '', 'Demo'), /image.*connection.*network/);
const payload = ui.templateImportPayload(bundle, '11', '22', '33', 'Mapped');
assert.equal(payload.baseImageId, 11);
assert.equal(payload.connectionId, 22);
assert.equal(payload.networkId, 33);
assert.equal(payload.name, 'Mapped');
assert.equal(payload.bundle, bundle);
console.log('PASS wave57 template bundle UI validation');
